import streamlit as st
import pandas as pd
import os

# Page configuration for mobile-friendly view
st.set_page_config(page_title="Letterboxd Stream Finder", layout="wide", page_icon="🎬")

st.title("🎬 Global Stream Finder")

# Path to the file generated by main.py
file_path = "data/unwatched_by_country.csv"

if os.path.exists(file_path):
    # Load data
    df = pd.read_csv(file_path)

    # --- SEARCH BAR ---
    search_query = st.text_input("🔍 Search for a movie title:", placeholder="e.g., The Handmaiden")

    # --- SIDEBAR FILTERS ---
    st.sidebar.header("Global Filters")
    
    # Option to view all countries or a specific one
    countries = ["All"] + sorted(df['country'].unique().tolist())
    selected_country = st.sidebar.selectbox("Select Country:", countries)
    
    # Provider Filter
    providers = ["All"] + sorted(df['provider'].unique().tolist())
    selected_provider = st.sidebar.selectbox("Select Service:", providers)

    # --- FILTERING LOGIC ---
    filtered_df = df.copy()

    # Filter by search text
    if search_query:
        filtered_df = filtered_df[filtered_df['title'].str.contains(search_query, case=False, na=False)]

    # Filter by country
    if selected_country != "All":
        filtered_df = filtered_df[filtered_df['country'] == selected_country]
        
    # Filter by provider
    if selected_provider != "All":
        filtered_df = filtered_df[filtered_df['provider'] == selected_provider]

    # --- DISPLAY RESULTS ---
    st.subheader(f"Results ({len(filtered_df)})")

    if not filtered_df.empty:
        # Reordering and cleaning up the view
        display_df = filtered_df[['title', 'year', 'country', 'provider']].reset_index(drop=True)
        st.dataframe(display_df, width='stretch')
    else:
        st.warning("No matches found. Try a different title or adjust your filters.")

else:
    st.error(f"⚠️ File {file_path} not found. Please run 'main.py' first.")